export const productData = {
    "data": {
        "draw": 1,
        "recordsTotal": 20,
        "recordsFiltered": 20,
        "data": [{
                "id": 5,
                "key": 0,
                "image": "<img src=\"http://salepropos.com/public/images/product/lalacrybabydoll.jpg\" height=\"80\" width=\"80\">",
                "name": "Baby doll",
                "code": "31261512",
                "brand": "HP",
                "category": "toy",
                "qty": 139,
                "unit": "Piece",
                "price": "120",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/5/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/5\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Baby doll\"",
                    " \"31261512\"",
                    " \"HP\"",
                    " \"toy\"",
                    " \"Piece\"",
                    " \"100\"",
                    " \"120\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"50\"",
                    " \"\"",
                    " \"5\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"139\"",
                    " \"lalacrybabydoll.jpg,15992893905761572515542825e4e2e433-e29b-4ca1-abb2-aad995574f2a_1.e4dc9f20c1d8b2999d66556ae0aa1600.jpeg\"]"
                ]
            },
            {
                "id": 3,
                "key": 1,
                "image": "<img src=\"http://salepropos.com/public/images/product/airphonesamsung.jpg\" height=\"80\" width=\"80\">",
                "name": "Earphone",
                "code": "85415108",
                "brand": "samsung",
                "category": "electronics",
                "qty": 163,
                "unit": "Piece",
                "price": "250",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/3/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/3\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Earphone\"",
                    " \"85415108\"",
                    " \"samsung\"",
                    " \"electronics\"",
                    " \"Piece\"",
                    " \"200\"",
                    " \"250\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"25\"",
                    " \"<p>Earphone with good <strong>sound quality.</strong></p> <p>jhjkhjkhjh @@</p>\"",
                    " \"3\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"163\"",
                    " \"airphonesamsung.jpg\"]"
                ]
            },
            {
                "id": 70,
                "key": 2,
                "image": "<img src=\"http://salepropos.com/public/images/product/zummXD2dvAtI.png\" height=\"80\" width=\"80\">",
                "name": "FERDZ",
                "code": "362664",
                "brand": "N/A",
                "category": "computer",
                "qty": 0,
                "unit": "Piece",
                "price": "500",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/70/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/70\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"FERDZ\"",
                    " \"362664\"",
                    " \"N/A\"",
                    " \"computer\"",
                    " \"Piece\"",
                    " \"500\"",
                    " \"500\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"70\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"0\"",
                    " \"zummXD2dvAtI.png\"]"
                ]
            },
            {
                "id": 71,
                "key": 3,
                "image": "<img src=\"http://salepropos.com/public/images/product/1614003414886oleos-fluidos.jpg\" height=\"80\" width=\"80\">",
                "name": "Fluidos de motor",
                "code": "79642873",
                "brand": "Lotto",
                "category": "accessories",
                "qty": 50,
                "unit": "Piece",
                "price": "100",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/71/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/71\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Fluidos de motor\"",
                    " \"79642873\"",
                    " \"Lotto\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"50\"",
                    " \"100\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"10\"",
                    " \"\"",
                    " \"71\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"50\"",
                    " \"1614003414886oleos-fluidos.jpg\"]"
                ]
            },
            {
                "id": 25,
                "key": 4,
                "image": "<img src=\"http://salepropos.com/public/images/product/SamsungGalaxyS9.jpg\" height=\"80\" width=\"80\">",
                "name": "Galaxy S9",
                "code": "72100265",
                "brand": "N/A",
                "category": "electronics",
                "qty": 26,
                "unit": "Piece",
                "price": "1000",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/25/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/25\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Galaxy S9\"",
                    " \"72100265\"",
                    " \"N/A\"",
                    " \"electronics\"",
                    " \"Piece\"",
                    " \"500\"",
                    " \"1000\"",
                    " \"vat@10\"",
                    " \"Exclusive\"",
                    " \"50\"",
                    " \"\"",
                    " \"25\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"26\"",
                    " \"SamsungGalaxyS9.jpg\"]"
                ]
            },
            {
                "id": 22,
                "key": 5,
                "image": "<img src=\"http://salepropos.com/public/images/product/iphoneX.jpg\" height=\"80\" width=\"80\">",
                "name": "iphone-X",
                "code": "97103461",
                "brand": "Apple",
                "category": "electronics",
                "qty": 45,
                "unit": "Piece",
                "price": "1000",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/22/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/22\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"iphone-X\"",
                    " \"97103461\"",
                    " \"Apple\"",
                    " \"electronics\"",
                    " \"Piece\"",
                    " \"800\"",
                    " \"1000\"",
                    " \"vat@10\"",
                    " \"Exclusive\"",
                    " \"20\"",
                    " \"\"",
                    " \"22\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"45\"",
                    " \"iphoneX.jpg\"]"
                ]
            },
            {
                "id": 13,
                "key": 6,
                "image": "<img src=\"http://salepropos.com/public/images/product/ldms.jpg\" height=\"80\" width=\"80\">",
                "name": "ldms",
                "code": "40624536",
                "brand": "N/A",
                "category": "computer",
                "qty": 0,
                "unit": "N/A",
                "price": "21",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/13/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/13\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"digital\"",
                    " \"ldms\"",
                    " \"40624536\"",
                    " \"N/A\"",
                    " \"computer\"",
                    " \"N/A\"",
                    " \"0\"",
                    " \"21\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"<p>Amazon Prime 1 Month<br />Price: 300tk</p> <p>User Ability: Max 2 Mobile User<br />Duration: 1 Month<br />Package: Premium</p>\"",
                    " \"13\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"0\"",
                    " \"ldms.jpg\"]"
                ]
            },
            {
                "id": 4,
                "key": 7,
                "image": "<img src=\"http://salepropos.com/public/images/product/lychee.jpg\" height=\"80\" width=\"80\">",
                "name": "lychee",
                "code": "38314290",
                "brand": "N/A",
                "category": "Fruits",
                "qty": 292,
                "unit": "Piece",
                "price": "2",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/4/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/4\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"lychee\"",
                    " \"38314290\"",
                    " \"N/A\"",
                    " \"Fruits\"",
                    " \"Piece\"",
                    " \"1\"",
                    " \"2\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"50\"",
                    " \"<p style=@text-align: center;@><em>sweet lychee from <strong>kalipur</strong>, bashkhali</em></p>\"",
                    " \"4\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"292\"",
                    " \"lychee.jpg\"]"
                ]
            },
            {
                "id": 2,
                "key": 8,
                "image": "<img src=\"http://salepropos.com/public/images/product/mango.jpg\" height=\"80\" width=\"80\">",
                "name": "mango",
                "code": "72782608",
                "brand": "N/A",
                "category": "Fruits",
                "qty": 3181,
                "unit": "Piece",
                "price": "12",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/2/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/2\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"mango\"",
                    " \"72782608\"",
                    " \"N/A\"",
                    " \"Fruits\"",
                    " \"Piece\"",
                    " \"8\"",
                    " \"12\"",
                    " \"vat@15\"",
                    " \"Inclusive\"",
                    " \"100\"",
                    " \"\"",
                    " \"2\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"3181\"",
                    " \"mango.jpg\"]"
                ]
            },
            {
                "id": 1,
                "key": 9,
                "image": "<img src=\"http://salepropos.com/public/images/product/toponemouse.jpg\" height=\"80\" width=\"80\">",
                "name": "Mouse",
                "code": "63920719",
                "brand": "samsung",
                "category": "computer",
                "qty": 191,
                "unit": "Piece",
                "price": "400",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/1/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/1\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Mouse\"",
                    " \"63920719\"",
                    " \"samsung\"",
                    " \"computer\"",
                    " \"Piece\"",
                    " \"320\"",
                    " \"400\"",
                    " \"vat@10\"",
                    " \"Exclusive\"",
                    " \"20\"",
                    " \"<p style=@text-align: center;@>11:11:30 AM<img src=@https://pbs.twimg.com/profile_images/900037286879838208/sZhajgua_400x400.jpg@ alt=@lioncoders@ width=@400@ height=@400@ /><span style=@background-color: #ccffff;@>hello world<br /></span></p>\"",
                    " \"1\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"191\"",
                    " \"toponemouse.jpg\"]"
                ]
            },
            {
                "id": 30,
                "key": 0,
                "image": "<img src=\"http://salepropos.com/public/images/product/PoloShirt.jpg\" height=\"80\" width=\"80\">",
                "name": "Polo Shirt",
                "code": "53467102",
                "brand": "N/A",
                "category": "accessories",
                "qty": 25,
                "unit": "Piece",
                "price": "100",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/30/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/30\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Polo Shirt\"",
                    " \"53467102\"",
                    " \"N/A\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"50\"",
                    " \"100\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"10\"",
                    " \"\"",
                    " \"30\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"25\"",
                    " \"PoloShirt.jpg\"]"
                ]
            },
            {
                "id": 10,
                "key": 1,
                "image": "<img src=\"http://salepropos.com/public/images/product/potato.jpeg\" height=\"80\" width=\"80\">",
                "name": "potato",
                "code": "212132",
                "brand": "N/A",
                "category": "food",
                "qty": 111,
                "unit": "kilogram",
                "price": "22",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/10/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/10\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"potato\"",
                    " \"212132\"",
                    " \"N/A\"",
                    " \"food\"",
                    " \"kilogram\"",
                    " \"10\"",
                    " \"22\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"10\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"111\"",
                    " \"potato.jpeg\"]"
                ]
            },
            {
                "id": 26,
                "key": 2,
                "image": "<img src=\"http://salepropos.com/public/images/product/zummXD2dvAtI.png\" height=\"80\" width=\"80\">",
                "name": "Samsung Set",
                "code": "39053411",
                "brand": "samsung",
                "category": "electronics",
                "qty": 0,
                "unit": "N/A",
                "price": "1250",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/26/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/26\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"combo\"",
                    " \"Samsung Set\"",
                    " \"39053411\"",
                    " \"samsung\"",
                    " \"electronics\"",
                    " \"N/A\"",
                    " \"0\"",
                    " \"1250\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"26\"",
                    " \"3,25\"",
                    " \"1,1\"",
                    " \"250,1000\"",
                    " \"0\"",
                    " \"zummXD2dvAtI.png\"]"
                ]
            },
            {
                "id": 31,
                "key": 3,
                "image": "<img src=\"http://salepropos.com/public/images/product/Shoe.jpg\" height=\"80\" width=\"80\">",
                "name": "Shoe",
                "code": "90471412",
                "brand": "N/A",
                "category": "accessories",
                "qty": 26,
                "unit": "Piece",
                "price": "300",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/31/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/31\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Shoe\"",
                    " \"90471412\"",
                    " \"N/A\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"250\"",
                    " \"300\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"10\"",
                    " \"\"",
                    " \"31\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"26\"",
                    " \"Shoe.jpg\"]"
                ]
            },
            {
                "id": 48,
                "key": 4,
                "image": "<img src=\"http://salepropos.com/public/images/product/1577165120189220px-Blue_Tshirt.jpg\" height=\"80\" width=\"80\">",
                "name": "T-shirt",
                "code": "93475396",
                "brand": "N/A",
                "category": "accessories",
                "qty": 37,
                "unit": "Piece",
                "price": "3",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/48/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/48\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"T-shirt\"",
                    " \"93475396\"",
                    " \"N/A\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"2\"",
                    " \"3\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"48\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"37\"",
                    " \"1577165120189220px-Blue_Tshirt.jpg\"]"
                ]
            },
            {
                "id": 62,
                "key": 5,
                "image": "<img src=\"http://salepropos.com/public/images/product/zummXD2dvAtI.png\" height=\"80\" width=\"80\">",
                "name": "Test variant",
                "code": "81145830",
                "brand": "N/A",
                "category": "toy",
                "qty": 3,
                "unit": "Piece",
                "price": "2",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/62/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/62\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Test variant\"",
                    " \"81145830\"",
                    " \"N/A\"",
                    " \"toy\"",
                    " \"Piece\"",
                    " \"1\"",
                    " \"2\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"62\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"3\"",
                    " \"zummXD2dvAtI.png\"]"
                ]
            },
            {
                "id": 60,
                "key": 6,
                "image": "<img src=\"http://salepropos.com/public/images/product/zummXD2dvAtI.png\" height=\"80\" width=\"80\">",
                "name": "testvar",
                "code": "32081679",
                "brand": "N/A",
                "category": "accessories",
                "qty": 1,
                "unit": "Piece",
                "price": "2",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/60/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/60\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"testvar\"",
                    " \"32081679\"",
                    " \"N/A\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"1\"",
                    " \"2\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"60\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"1\"",
                    " \"zummXD2dvAtI.png\"]"
                ]
            },
            {
                "id": 33,
                "key": 7,
                "image": "<img src=\"http://salepropos.com/public/images/product/zummXD2dvAtI.png\" height=\"80\" width=\"80\">",
                "name": "tissue",
                "code": "8941161008066",
                "brand": "N/A",
                "category": "accessories",
                "qty": 38,
                "unit": "Piece",
                "price": "20",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/33/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/33\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"tissue\"",
                    " \"8941161008066\"",
                    " \"N/A\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"10\"",
                    " \"20\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"33\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"38\"",
                    " \"zummXD2dvAtI.png\"]"
                ]
            },
            {
                "id": 32,
                "key": 8,
                "image": "<img src=\"http://salepropos.com/public/images/product/1572759415477product-page-fresh-breath.jpg\" height=\"80\" width=\"80\">",
                "name": "Toothpaste",
                "code": "859875003032",
                "brand": "N/A",
                "category": "accessories",
                "qty": 30,
                "unit": "Piece",
                "price": "10",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/32/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/32\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"Toothpaste\"",
                    " \"859875003032\"",
                    " \"N/A\"",
                    " \"accessories\"",
                    " \"Piece\"",
                    " \"5\"",
                    " \"10\"",
                    " \"N/A\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"32\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"30\"",
                    " \"1572759415477product-page-fresh-breath.jpg\"]"
                ]
            },
            {
                "id": 61,
                "key": 9,
                "image": "<img src=\"http://salepropos.com/public/images/product/zummXD2dvAtI.png\" height=\"80\" width=\"80\">",
                "name": "TV",
                "code": "32703342",
                "brand": "samsung",
                "category": "electronics",
                "qty": 16,
                "unit": "Piece",
                "price": "10000",
                "options": "<div class=\"btn-group\">\n                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Action\n                              <span class=\"caret\"></span>\n                              <span class=\"sr-only\">Toggle Dropdown</span>\n                            </button>\n                            <ul class=\"dropdown-menu edit-options dropdown-menu-right dropdown-default\" user=\"menu\">\n                            <li>\n                                <button=\"type\" class=\"btn btn-link view\"><i class=\"fa fa-eye\"></i> View</button>\n                            </li><li>\n                            <a href=\"http://salepropos.com/products/61/edit\" class=\"btn btn-link\"><i class=\"fa fa-edit\"></i> Edit</a>\n                        </li><form method=\"POST\" action=\"http://salepropos.com/products/61\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"i1xLiPgeFC6UzMPFYutU502V77eI47Ts77L8y8AC\">\n                            <li>\n                              <button type=\"submit\" class=\"btn btn-link\" onclick=\"return confirmDelete()\"><i class=\"fa fa-trash\"></i> Delete</button> \n                            </li></form>\n                        </ul>\n                    </div>",
                "product": [
                    "[ \"standard\"",
                    " \"TV\"",
                    " \"32703342\"",
                    " \"samsung\"",
                    " \"electronics\"",
                    " \"Piece\"",
                    " \"3000\"",
                    " \"10000\"",
                    " \"vat@15\"",
                    " \"Exclusive\"",
                    " \"\"",
                    " \"\"",
                    " \"61\"",
                    " \"\"",
                    " \"\"",
                    " \"\"",
                    " \"16\"",
                    " \"zummXD2dvAtI.png\"]"
                ]
            }
        ]
    }
}